### ISSUE TITLE
Problems with TP-Link Connect for Plugs in new Smartthings app

### ISSUE THREAD

**Issue by bpinsky123** [DaveGut/SmartThings_Cloud-Based_TP-Link-Plugs-Switches-Bulbs#15]
I was able to install the smartapp in the Smartthings Classic app and add my TP-Link Plug.  In the Classic app, it shows the device and gives me a button for on/off.  If I go into the new Smartthings app, the device is there but there is no button for on/off and if I click on the device, it says "Can't connect to device. Check device and try again."   Also, the plug is not available as device to add to my custom automations.

Lastly, if go to Automations and click on the TP-Link Cloud Connect app, there is a place for my TP-Link Password, but not the Userid.

**Comment by DaveGut** [comment]
Not yet compatible with the new app.  Awaiting on SmartThings.

**Comment by Master649** [comment]
I was having the same issue with the new Smartthiings app.  

Do we have an idea of when the compatibility issue might be fixed?

**Comment by DaveGut** [comment]
I do not.  I do not believe there is any schedule or plan but work and work harder.  It is VERY complex and may end up not possible for all of the myriad of Smart Apps and Device Handlers in the environment.

**Comment by bpinsky123** [comment]
Thanks for the reply Dave.  In looking at the new Smartthings app more closely, it's clear they haven't done all the work to allow for customer defined SmartApps yet.  So while you can create them on the IDE portal and they show up in the app, the lack of any UI that mentions adding a Smartapp other than the recommended ones seems to point to missing functionality.

Guess I'll just have to wait :-)

**Comment by creekmorejr** [comment]
Dave,

Thanks for using your expertise in putting together the code for the TP-Link plugs.  I am new at this, but I get this error when I try to save after my 3 devices are found:  70e19e18-d76d-4482-88aa-f21c51785ec1 9:10:40 PM: error physicalgraph.app.exception.UnknownDeviceTypeException: Device type '(Cloud) TP-Link Plug-Switch' in namespace 'davegut' not found. @line 359 (doCall)

I thought that it might be that I had wrong location selected, but the locations tab show the right one.  What did I do wrong?  Thanks for your help.

Richard

**Comment by DaveGut** [comment]
Go and get the new switch device handler.  Had to split the switch and plug into two to take advantage of the new phone app.



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by creekmorejr** [comment]
Dave,

Thanks for the information.  I will try this weekend.

Richard Creekmore
Sent from my iPhone

On Oct 28, 2018, at 21:36, David Gutheinz <notifications@github.com<mailto:notifications@github.com>> wrote:

Go and get the new switch device handler. Had to split the switch and plug into two to take advantage of the new phone app.



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by DaveGut** [comment]
Close.  No response.
