### ISSUE TITLE
cant connect tp link to smarthings

### ISSUE THREAD

**Issue by fdavidgespinosa** [DaveGut/SmartThings_Cloud-Based_TP-Link-Plugs-Switches-Bulbs#16]
Hello DaveGut: 
I have been trying to make the connection of my TP Link smart plug HS105 with smarthings following these steps but I do not succeed, what am I doing wrong? Could you guide me?

Pre requirements:
HS105 configured and running with the KASA app, enabled the control via internet and running Account used fdavidgespinosa1@gmail.com

On the smarthings website: (account fdavidgespinosa@hotmail.com) 
1.1 My Device Handlers/Add Handler using the code of “(Cloud) TP-Link Plug-Switch.groovy”, saving and publishing 
1.2  Connection to github SmartThingsPublic Account fdavidgespinosa@hotmail.com
1.3 My Smart apps
New app from code using “TPLink Cloud Connect V2.groovy”, save and publish

1.4 do not change the name or the file name of the device (HS015) shown in the documentation, I do not know where to do it or if it is necessary to do it.

1.5 in the Smathings Classic 2.16.1 application for android account fdavidgespinosa@hotmail.com automation / add smart app / + My apps Select “TP-Link Cloud connect” put email address, KASA APP password and “initial install” and next then SAVE and an error appears in a red box that says "Error - bad state. Unable to complete page configuration"

**Comment by DaveGut** [comment]
Assure you have selected your location prior to installing the Smart App and Device Handler.  I just tested on a new HS-105 and did not see any errors.

Additionally, try again and turn on Live Logging for the Smart App.  Need any error messages received there to point to potential errors.

Dave

**Comment by fdavidgespinosa** [comment]
> Assure you have selected your location prior to installing the Smart App and Device Handler. I just tested on a new HS-105 and did not see any errors.
> 
> Additionally, try again and turn on Live Logging for the Smart App. Need any error messages received there to point to potential errors.
> 
> Dave


Thanks for your words, do what you tell me. I have already found another way to make the connection (I think it is easier) by adding a device in smarthings of the emulated switch type and then linked to IFTTT, the trigger of the action is harmony logitech. It works for both TP link and wemo :)

**Comment by DaveGut** [comment]
closed.
