### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by afloyd2000** [DaveGut/SmartThings_Cloud-Based_TP-Link-Plugs-Switches-Bulbs#17]
The Service sees the devices, and I have updated my Password.  I keep getting "unexpected error"  I am using both the Connect and Classic Apps, as I cannot add the Smart App in the new version.

**Comment by DaveGut** [comment]
The Smart App and Handler are not yet compatible with the new Connect App.  Waiting on SmartThings.

**Comment by DaveGut** [comment]
You can not add any smart app in the new Phone App.  You must first install using classic.

**Comment by afloyd2000** [comment]
Yes,

Thanks,

I was able to get them working well using the old app.



Sent from my iPhone

On Nov 17, 2018, at 11:58 AM, David Gutheinz <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #17<https://github.com/DaveGut/SmartThings_Cloud-Based_TP-Link-Plugs-Switches-Bulbs/issues/17>.
