### ISSUE TITLE
Error when adding HS220

### ISSUE THREAD

**Issue by rslonee** [DaveGut/SmartThings_Cloud-Based_TP-Link-Plugs-Switches-Bulbs#18]
Hi,

I’m receiving this error in the IDE log when attempting to add a new device (HS220). java.lang.NullPointerException: Cannot get property 'value' on null object @line 199 (doCall)

Any idea what can be done to resolve?

Thanks for investing your time in this project!

**Comment by DaveGut** [comment]
Close.  Not respose
