### ISSUE TITLE
HS220 will not operate as a dimmer

### ISSUE THREAD

**Issue by sunnyghai** [DaveGut/SmartThings_Cloud-Based_TP-Link-Plugs-Switches-Bulbs#21]
Hi @DaveGut, 

First of all, thank you for all the great work you've done on TP-Link ST integration. Generally, all of your DH and SA works great. I'm stuck trying to get my HS220 to turn on as a dimmer, much less get the proper dimming levels.

I'm using CoRE to turn on the switch and set levels. With my busy schedule, I just haven't had the time to learn WebCore. My HS220 shows up both as a light switch and a dimmable light or dimmer in the SA. This is unusual, since my devices only show up as one or the other.  When used as a light switch, it works great.  As a dimmer, the HS220 does not turn on, though I can see that a request has been sent in the recent tab of the device in the ST app. 

I originally posted this under the hub-based DH section... realizing my error, I removed it and posted it here.  Sorry for the confusion.

Can you help or offer a suggestion?

**Comment by DaveGut** [comment]
Using the classic APP, what does the device look like?  Can you control the dimming feature?  If not, I will create a special Device Handler that will provide enhanced event logging on the dimming function.  This will allow you to use live logging to collect data and send to me.  I can then try to figure out what is not working.

**Comment by sunnyghai** [comment]
@DaveGut , I should have been more specific.  I am able to control the dimming feature with ST in the classic app.  My problem is when I use CoRE.  I want my motion sensors to trigger the lights.  The CoRE piston is called "Kitchen Island Test."  I have included a snapshot of the device, the piston in CoRE and a Recent log.  In the Recent log, I turned the light on at 3:01 PM in the Device tab in the classic app.  All the other events were done by the CoRE piston. However, they do not turn on.   I'm basically trying to have my motion sensors turn on the Kitchen Island Lights using CoRE.  No joy at the moment.

I use CoRE for all my other lighting controls and it works great.  I am not sure why it doesn't work for the HS220.


![device](https://user-images.githubusercontent.com/31091096/48665337-a0d4a400-ea7a-11e8-9d55-9cf6d289b57a.jpg)
![piston](https://user-images.githubusercontent.com/31091096/48665338-a336fe00-ea7a-11e8-81a8-cd72a5f28640.PNG)
![recent](https://user-images.githubusercontent.com/31091096/48665339-a5995800-ea7a-11e8-904a-796ad9d90bbd.PNG)

**Comment by DaveGut** [comment]
First, assure that you pass an integer value to the light without the "%" sign,  Any decimal value will read as zero (i.e,, .5).  Then, try using the webcore interface with LiveLogging on.  Live logging will have display the status whenever a command is sent.

There is also an attribute you can read in core:  level

**Comment by sunnyghai** [comment]
![img_2868](https://user-images.githubusercontent.com/31091096/48665902-20677080-ea85-11e8-8aeb-c44dc0b2b8c6.png)
![img_2867](https://user-images.githubusercontent.com/31091096/48665905-2fe6b980-ea85-11e8-922e-9c5e061bdc80.png)
@DaveGut ,

I got CoRE to turn on the Island light by adding a "Turn On" command after "Set Level to 50%!"  This is unusual since none of my other dimmable devices require this.

**Comment by DaveGut** [comment]
In the IDE, open up the Device Handler.  You will see the section below:

def setLevel(percentage) {
	percentage = percentage as int
    if (percentage == 0) {
    	percentage = 1
    }
	sendCmdtoServer("""{"smartlife.iot.dimmer":{"set_brightness":{"brightness":${percentage}}}}""", "deviceCommand", "commandResponse")
}

Change to the below:
def setLevel(percentage) {
**log.debug "At setLevel, percentage is ${percentage}"**
	percentage = percentage as int
    if (percentage == 0) {
    	percentage = 1
    }
	sendCmdtoServer("""{"smartlife.iot.dimmer":{"set_brightness":{"brightness":${percentage}}}}""", "deviceCommand", "commandResponse")
}

Open live logging and select your device.  Then run the testing.  This will tell us if there is a problem in the level format.

**Comment by sunnyghai** [comment]
I'm sorry, newbie question, but where do I set up live logging?  Is this in CoRE or WebCore?

**Comment by DaveGut** [comment]
Live Logging is in the IDE.  It is one of the tabs at the top.

**Comment by sunnyghai** [comment]
I ran the test and set the level to 75% in the CoRE piston.  I can see the 75% in the live logging, but the lights are not turning on.

**Comment by DaveGut** [comment]
I am at a loss.  This is the same path as the classic phone app.  Can you copy and paste the log e try?



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by sunnyghai** [comment]
I just sent you the logs via outlook email.

**Comment by DaveGut** [comment]
Good info.  Switch is not turning on with a level command (like the bulbs do).  DH is at fault.

Try adding the line below after the line you added earlier.  If it works, let me know ASAP.  I will update the package (but yours will already be updated).

	sendCmdtoServer('{"system":{"set_relay_state":{"state": 1}}}', "deviceCommand", "commandResponse")

**Comment by sunnyghai** [comment]
@DaveGut , you're the man!  That did the trick.  Thank you.

**Comment by DaveGut** [comment]
Thanks for working with me.  I like things to be correct.  I will be updating all device handlers (SmartThings and Hubitat) to correct this problem.

Dave

**Comment by sunnyghai** [comment]
Dave,

Unfortunately, I am running into a new problem adding my second HS220 using the new TP-Linke SmartThings Manager.  In live logging, I am getting an error: 23093565-9258-4d07-9a2a-b92ba34e0911  5:27:53 PM: debug Error Adding null: physicalgraph.app.exception.UnknownDeviceTypeException: Device type 'TP-Link Smart Dimming Switch' in namespace 'davegut' not found.

I have both the TP-Link (unofficial) Connect apps and the new TP-Link SmartThings Manager loaded in my ST app.  With the exception of the first HS220, everything all of my 15 plugs and 5 switches were installed with the unofficial app.  With the new app, it finds 18 total devices, some which are already installed.  I was only installing he HS220.  Is this part of the problem?

**Comment by DaveGut** [comment]
No, the error indicates that the device handler is not installed.  There is a unique device handler for the dimming switch.  As far as the other error, I do not know why.  I will be working this next week to troubleshoot the new app.  Causing WAY TOO MANY PROBLEMS.  May go back to far simpler app.

Dav

**Comment by sunnyghai** [comment]
Dave,

My first HS220 is using "(Cloud) TP-Link Dimming Switch."  Why isn't it taking it?

Are the two apps able to peacefully exist with each other or should I deleted the first one?

Thanks,

Sunny

**Comment by sunnyghai** [comment]
I have both.  I suspect that is probably the problem.  I tried to remove the old App but am getting errors that the app is being used by more then one users.  This could be the case since I am also managing my Dad’s hub.

On Dec 2, 2018, at 10:25 PM, David Gutheinz <notifications@github.com> wrote:

You should only use one. They can co-exist; however, on installation, you will get errors if a device is already installed.

**Comment by sunnyghai** [comment]
Here’s a thought: since I only have 5 devices from the new app, I would delete those devices, remove the new app, and update the old app with the new code. Do you think that would work?


Sent from Yahoo Mail for iPad


On Sunday, December 2, 2018, 10:26 PM, David Gutheinz <notifications@github.com> wrote:

May be a repeat.

Error is indicative that the Device Handler was not installed (or you are using an older version with the new application).
